#!/bin/bash

CGI_ROOT=/usr/lib/cgi-bin
HTML_ROOT=/var/www/html
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# #########################
# First build CGI directory
# #########################

# Make sure directory CGI_ROOT exists
if [[ ! -d $CGI_ROOT ]]; then
	echo Directory $CGI_ROOT does not exist;
	exit;
else
	echo Directory $CGI_ROOT exists
fi

# Completely clear out directory CGI_ROOT
CUR_DIR=$(pwd)
cd $CGI_ROOT
rm -rf *
cd $CUR_DIR

# Create directory kmzout
mkdir $CGI_ROOT/kmzout
chown www-data:www-data $CGI_ROOT/kmzout

# Create directory KmlFileImages
mkdir $CGI_ROOT/KmlFileImages

# Copy all the cgi related files to CGI_ROOT
cp -a $SCRIPT_DIR/usr_lib_cgi-bin/* $CGI_ROOT 

# PERMISSIONS 
# Set evey file and directory to root:root and permissions to 755
chown -R root:root $CGI_ROOT/*
chmod -R 755 $CGI_ROOT/*

# Set needed special permissions
chown www-data:www-data $CGI_ROOT/kmzout
chown -R www-data:www-data $CGI_ROOT/KmlFileImages
chown www-data:www-data $CGI_ROOT/CGI-exe.cgi

chmod 700 $CGI_ROOT/CGI-exe.cgi
chmod 766 $CGI_ROOT/KmlFileImages
chmod 755 $CGI_ROOT/KmlFileImages/*
chmod 700 $CGI_ROOT/kmzout


# ########################
# NOW BUILD HTML DIRECTORY
# ########################

# Make sure directory HTML_ROOT exists
if [[ ! -d $HTML_ROOT ]]; then
	echo Directory $HTML_ROOT does not exist;
	exit;
else
	echo Directory $HTML_ROOT exists
fi

# Completely clear out directory HTML_ROOT
CUR_DIR=$(pwd)
cd $HTML_ROOT
rm -rf *
cd $CUR_DIR

# Create directory kmzout
mkdir $HTML_ROOT/kmzout
chown www-data:www-data $HTML_ROOT/kmzout

# Copy all the site related files to HTML_ROOT
cp -a $SCRIPT_DIR/var_www_html/* $HTML_ROOT 

# PERMISSIONS 
# Set evey file and directory to root:root and permissions to 755
chown -R root:root $HTML_ROOT/*
chmod -R 755 $HTML_ROOT/*

# Set needed special permissions
chown www-data:www-data $HTML_ROOT/kmzout
chmod 766 $HTML_ROOT/kmzout
